---
title: "sb_birds"
format: html
editor: visual
---

```{r}
library(here)
library(tidyverse)
library(sf)
library(tmap)

```
```{r}
sb_protected_areas <- st_read(here("week3","data", "cpad_super_units_sb.shp")) %>%  
  st_transform("ESRI:102009")

sb_city_boundaries <- st_read(here("week3","data", "sb_city_boundaries_2003.shp")) %>% 
  st_transform("ESRI:102009")

sb_county_boundary <- st_read(here("week3", "data", "sb_county_boundary_2020.shp")) %>%  
  st_transform("ESRI:102009")

aves <- st_read(here("week3","data", "aves_observations_2020_2024.shp")) %>% 
  st_transform("ESRI:102009")
```
```{r}
tm_shape(sb_county_boundary) + 
  tm_fill() + 
tm_shape(sb_protected_areas) + 
  tm_fill(col = "green", alpha = 0.2) + 
tm_shape(aves_PA_subset) + 
  tm_dots(size = 0.3)
```
```{r}
aves_PA_subset <- sb_protected_areas[aves, ] # Subset using aves data set 

nrow(aves_PA_subset) # Check number of rows corresponding to bird observations
```

```{r}

st_crs(sb_protected_areas)$units

protected_buffer_5km <- st_buffer(sb_protected_areas, dist = 5000)

birds_protected_buffer_5km[aves, ]
```

